# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|

  config.expect_with :rspec do |expectations|

    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|

    mocks.verify_partial_doubles = true
  end

end


def create_user_bobby
  visit new_user_url
  fill_in 'Username', with: "bobby"
  fill_in 'Password', with: "damnitbobby"
  click_on "Create User"
end

def create_user_hank
  visit new_user_url
  fill_in 'Username', with: "hank"
  fill_in 'Password', with: "damnitbobby"
  click_on "Create User"
end

def create_bad_user
  visit new_user_url
  fill_in 'Password', with: "damn"
  click_on "Create User"
end

def logout_user
  click_on "Log Out"
end


def login_user_bobby
  visit new_session_url
  fill_in 'Username', with: 'bobby'
  fill_in 'Password', with: 'damnitbobby'
  click_on 'Sign In'
end



def create_goal_private
  visit new_goal_url
  fill_in 'Title', with: "Eat more veggies"
  fill_in 'Content', with: "Yum Yum Yum"
  check('Private')
  click_on 'Create Goal'
end

def create_goal_public
  visit new_goal_url
  fill_in 'Title', with: "Eat less meat"
  fill_in 'Content', with: "Meat is Murder!!!!!"
  click_on 'Create Goal'
end

def create_bad_goal
  visit new_goal_url
  fill_in 'Content', with: "Meat is Murder!!!!!"
  click_on 'Create Goal'
end

def create_multiple_users
  create_user_bobby
  logout_user
  create_user_hank
end

def create_user_comment
  create_multiple_users
  visit user_url(User.first)
  fill_in 'Comment', with: "good luck"
  click_on 'Add Comment'
end

def create_bad_user_comment
  create_multiple_users
  visit user_url(User.first)
  click_on 'Add Comment'
end

def create_goal_comment
  create_multiple_users; create_goal_public
  logout_user; login_user_bobby
  visit goal_url(Goal.first)
  fill_in 'Comment', with: "that is some hippie nonsense"
  click_on 'Add Comment'
end

def create_bad_goal_comment
  create_multiple_users; create_goal_public
  logout_user; login_user_bobby
  visit goal_url(Goal.first)
  click_on 'Add Comment'
end
